image: circleci/openjdk:8-jdk

build_and_test:
  script:
    - sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - sudo apt-get update
    - sudo apt-get -y install google-chrome-stable
    - ls
    - sudo chmod 777 src/test/resources/chromedriver.exe
    - sudo apt-get install libxi6 libgconf-2-4
    - sudo apt-get -y install xvfb gtk2-engines-pixbuf
    - sudo apt-get -y install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable
    - sudo apt-get install xvfb
    - sudo apt-get -y install imagemagick x11-apps
    - Xvfb :0 -ac &
    - export DISPLAY=:99
    - mvn test
